/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class PritAccessoriesApi {
    protected basePath = 'http://localhost:8080/adms-pri/api/pri';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * PriBussinessSpec.addProjAccessories
     * สำหรับการบันทึกข้อมูลProject Accessories
     * @param body 
     */
    public addProjAccessories (body?: models.ProjAccessoriesAddBean, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/pritAccessories';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.editProjAccessories
     * สำหรับการแก้ไขข้อมูลProject Accessories
     * @param body 
     */
    public editProjAccessories (body?: models.ProjAccessoriesBean, extraHttpRequestParams?: any ) : Observable<models.ProjAccessoriesBean> {
        const path = this.basePath + '/pritAccessories';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.getProjAccessoriesByRef
     * สำหรับการค้นหาตารางข้อมูลProject Accessories ตาม Primary key
     * @param projAccessoriesRef 
     */
    public getProjAccessoriesByRef (projAccessoriesRef: number, extraHttpRequestParams?: any ) : Observable<models.PritAccessories> {
        const path = this.basePath + '/pritAccessories/{projAccessoriesRef}'
            .replace('{' + 'projAccessoriesRef' + '}', String(projAccessoriesRef));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'projAccessoriesRef' is not null or undefined
        if (projAccessoriesRef === null || projAccessoriesRef === undefined) {
            throw new Error('Required parameter projAccessoriesRef was null or undefined when calling getProjAccessoriesByRef.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.getProjAccessoriesList
     * สำหรับการค้นหาตารางข้อมูลProject Accessories
     * @param projCode 
     * @param start 
     * @param size 
     */
    public getProjAccessoriesList (projCode: string, start?: number, size?: number, extraHttpRequestParams?: any ) : Observable<Array<models.ProjAccessoriesBean>> {
        const path = this.basePath + '/pritAccessories/projCode/{projCode}'
            .replace('{' + 'projCode' + '}', String(projCode));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'projCode' is not null or undefined
        if (projCode === null || projCode === undefined) {
            throw new Error('Required parameter projCode was null or undefined when calling getProjAccessoriesList.');
        }
        if (start !== undefined) {
            queryParameters.set('start', String(start));
        }

        if (size !== undefined) {
            queryParameters.set('size', String(size));
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.removeProjAccessoriesByRef
     * สำหรับการลบข้อมูลProject Accessories ตาม Primary Key
     * @param projAccessoriesRef 
     */
    public removeProjAccessoriesByRef (projAccessoriesRef: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/pritAccessories/{projAccessoriesRef}'
            .replace('{' + 'projAccessoriesRef' + '}', String(projAccessoriesRef));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'projAccessoriesRef' is not null or undefined
        if (projAccessoriesRef === null || projAccessoriesRef === undefined) {
            throw new Error('Required parameter projAccessoriesRef was null or undefined when calling removeProjAccessoriesByRef.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.removeProjAccessoriesList
     * สำหรับการลบข้อมูลProject Accessories
     * @param body 
     */
    public removeProjAccessoriesList (body?: Array<number>, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/pritAccessories';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
