/**
 * CDGS Service API
 * Authorize Service Provider
 *
 * OpenAPI spec version: 1.0.0
 * Contact: anuchit.i@cdg.co.th
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class RoleApi {
    // protected basePath = 'http://10.254.40.27:8000/cdgs-authorize-services/api/v1';
    protected basePath = '/cdgs-authorize-services/api/v1';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * List Menu By Role Id User
     * Service แสดง Menu ทั้งหมดของ User ตาม Role Id ที่กำหนด
     * @param roleId Role Id
     */
    public menuUserRoleroleIdGet (roleId: number, extraHttpRequestParams?: any ) : Observable<Array<models.FwMenuBean>> {
        const path = this.basePath + '/menu/user/role/${roleId}'
            .replace('{' + 'roleId' + '}', String(roleId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'roleId' is not null or undefined
        if (roleId === null || roleId === undefined) {
            throw new Error('Required parameter roleId was null or undefined when calling menuUserRoleroleIdGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Get Permission By Role Id
     * Service แสดง Permission ทั้งหมดของ User ตาม Role Id ที่กำหนด
     * @param roleId Role Id
     */
    public permissionRoleroleIdGet (roleId: number, extraHttpRequestParams?: any ) : Observable<Array<models.FwPermissionBean>> {
        const path = this.basePath + '/permission/role/${roleId}'
            .replace('{' + 'roleId' + '}', String(roleId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'roleId' is not null or undefined
        if (roleId === null || roleId === undefined) {
            throw new Error('Required parameter roleId was null or undefined when calling permissionRoleroleIdGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * List Role User
     * Service แสดง Role ทั้งหมดของ User
     */
    public roleUserGet (extraHttpRequestParams?: any ) : Observable<models.FwRoleBean> {
        const path = this.basePath + '/role/user';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
