/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class PritDeliverApi {
    protected basePath = '/api/pri';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * PriBussinessSpec.addProjDeliver
     * สำหรับการบันทึกข้อมูลการส่งมอบโครงการ
     * @param body 
     */
    public addProjDeliver (body?: models.ProjDeliverAddBean, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/pritDeliver';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.editProjDeliver
     * สำหรับการแก้ไขข้อมูลการส่งมอบโครงการ
     * @param body 
     */
    public editProjDeliver (body?: models.ProjDeliverBean, extraHttpRequestParams?: any ) : Observable<models.ProjDeliverBean> {
        const path = this.basePath + '/pritDeliver';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.getProjDeliverByRef
     * สำหรับการค้นหาตารางข้อมูลการส่งมอบโครงการ ตาม Primary key
     * @param projDeliverRef 
     */
    public getProjDeliverByRef (projDeliverRef: number, extraHttpRequestParams?: any ) : Observable<models.PritDeliver> {
        const path = this.basePath + '/pritDeliver/{projDeliverRef}'
            .replace('{' + 'projDeliverRef' + '}', String(projDeliverRef));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'projDeliverRef' is not null or undefined
        if (projDeliverRef === null || projDeliverRef === undefined) {
            throw new Error('Required parameter projDeliverRef was null or undefined when calling getProjDeliverByRef.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.getProjDeliverList
     * สำหรับการค้นหาตารางข้อมูลการส่งมอบโครงการ
     * @param projCode 
     * @param start 
     * @param size 
     */
    public getProjDeliverList (projCode: string, start?: number, size?: number, extraHttpRequestParams?: any ) : Observable<Array<models.ProjDeliverBean>> {
        const path = this.basePath + '/pritDeliver/projCode/{projCode}'
            .replace('{' + 'projCode' + '}', String(projCode));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'projCode' is not null or undefined
        if (projCode === null || projCode === undefined) {
            throw new Error('Required parameter projCode was null or undefined when calling getProjDeliverList.');
        }
        if (start !== undefined) {
            queryParameters.set('start', String(start));
        }

        if (size !== undefined) {
            queryParameters.set('size', String(size));
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.removeProjDeliverByRef
     * สำหรับการลบข้อมูลการส่งมอบโครงการ ตาม Primary Key
     * @param projDeliverRef 
     */
    public removeProjDeliverByRef (projDeliverRef: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/pritDeliver/{projDeliverRef}'
            .replace('{' + 'projDeliverRef' + '}', String(projDeliverRef));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'projDeliverRef' is not null or undefined
        if (projDeliverRef === null || projDeliverRef === undefined) {
            throw new Error('Required parameter projDeliverRef was null or undefined when calling removeProjDeliverByRef.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * PriBussinessSpec.removeProjDeliverList
     * สำหรับการลบข้อมูลการส่งมอบโครงการ
     * @param body 
     */
    public removeProjDeliverList (body?: Array<number>, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/pritDeliver';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
